name: vacation-checker-slack-bot
# on:
#   schedule:
#   - cron: '0 0 * * SUN'
on:
  push:
    branches:
      - main
jobs:
  check_vacation_members_and_post_slack_message:
    runs-on: ubuntu-latest
    steps:
      - name: action code checkout
        uses: actions/checkout@v3
      
      - name: create .env file
        run: |
          echo "SLACK_BOT_USER_OAUTH_TOKEN=${{ secrets.SLACK_BOT_USER_OAUTH_TOKEN }}" > .env
          echo "VACATION_NOTICE_CHANNEL_NAME=${{ secrets.VACATION_NOTICE_CHANNEL_NAME }}" >> .env
          echo "REPO_URL=${{ secrets.REPO_URL }}" >> .env
          echo "REPO_NAME=${{ secrets.REPO_NAME }}" >> .env
          
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: check vacations and post message
        run: python src/main.py
